# Generated by Django 3.2.15 on 2023-05-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_loc', models.CharField(max_length=100)),
                ('delivery_loc', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Грузы',
                'verbose_name_plural': 'Груз',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=30)),
                ('lng', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Локации',
                'verbose_name_plural': 'Локация',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_num', models.CharField(default='1786G', max_length=5, unique=True)),
                ('load_cap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('curr_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.locations')),
            ],
            options={
                'verbose_name': 'Машины',
                'verbose_name_plural': 'Машина',
            },
        ),
    ]
