# Generated by Django 3.2.15 on 2023-05-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_auto_20230527_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_num', models.CharField(default='7793D', max_length=5, unique=True)),
                ('load_cap', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.AddField(
            model_name='car',
            name='curr_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.location'),
        ),
    ]
