# Generated by Django 3.2.15 on 2023-05-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_auto_20230528_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='curr_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_loc', to='cargo.location'),
        ),
        migrations.AlterField(
            model_name='car',
            name='unique_num',
            field=models.CharField(default='6938J', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='delivery_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_locs', to='cargo.location'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pick_up_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_up_locs', to='cargo.location'),
        ),
    ]
